//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenteFit.Modelos
{
    using System;
    using System.Collections.Generic;

    public partial class Actividad
    {
        public Actividad()
        {
            this.ListaEspera = new HashSet<ListaEspera>();
            this.Reserva = new HashSet<Reserva>();
        }

        // Propiedades de la clase Actividad
        public int ActividadID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Intensidad { get; set; }
        public int PlazasTotales { get; set; }
        public DateTime Horario { get; set; }
        public int SalaID { get; set; }
        public int MonitorID { get; set; }

        // Navegación
        public virtual Sala Sala { get; set; }
        public virtual Monitor Monitor { get; set; }
        public virtual ICollection<ListaEspera> ListaEspera { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }

        // Propiedad calculada para obtener las plazas disponibles
        public int PlazasDisponibles
        {
            get
            {
                return PlazasTotales - Reserva.Count;
            }
        }
    }
}
